services:
  argocd:
    image: quay.io/argoproj/argocd:v2.12.3 
    container_name: argocd
    environment:
      - ARGOCD_API_SERVER_INSECURE=true
      - KUBERNETES_MASTER=https://kubernetes.default.svc
      - ARGOCD_KUBE_CONFIG_PATH=/app/config/kubeconfig.yaml
    ports:
      - "8080:8080"  
      - "8082:8081"   
    volumes:
      - ./data/argocd:/var/lib/argocd
      - ./kubeconfig.yaml:/app/config/kubeconfig.yaml  
    command: ["argocd-server", "--insecure"] 
    restart: unless-stopped
