services:
  argocd-server:
    image: argoproj/argocd:latest
    container_name: argocd-server
    ports:
      - "8080:8080"  # Argo CD UI
      - "8082:8081"  # Argo CD API
    environment:
      - ARGOCD_API_SERVER=argocd-server:8081
      - ARGOCD_UI_SERVER=argocd-server:8080
      - KUBECONFIG=/app/config/kubeconfig.yaml
      - KUBERNETES_MASTER=https://api.kube1.okd.piensoluegoinstalo.com:6443
    volumes:
      - argocd-data:/app/config
      - ./kubeconfig.yaml:/app/config/kubeconfig.yaml
    command:
      - argocd-server
      - --insecure
    depends_on:
      - argocd-repo-server
      - argocd-redis

  argocd-repo-server:
    image: argoproj/argocd:latest
    container_name: argocd-repo-server
    environment:
      - ARGOCD_API_SERVER=argocd-server:8081
    volumes:
      - ./argocd-data:/app/config
    command:
      - argocd-repo-server

  argocd-redis:
    image: redis:alpine
    container_name: argocd-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
